plugins = []
headers = []
redirects = []

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["node-fetch"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[functions."*"]

[build]
publish = "build"
publishOrigin = "ui"
commandOrigin = "ui"
command = "npm run build"
functions = "netlify/functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]